### ISSUE TITLE
View own telemetry report

### ISSUE THREAD

**Issue by littleskunk** [Storj/statusify#5]
As farmer I would like to verify my telemetry report to make sure everything is correct for the reward calculation. I don't need a perfect website or a complete node list. An easy API call like `GET https://status.storj.io/8f22f4efdacf9de3333f8cb2e28f6e534173d705` (my test nodeID) would be perfect.

I would like to verify:
Free and used storage
Upload and download bandwidth
Contact information
Payout address
Last report timestamp
Uptime if possible

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
