### ISSUE TITLE
Error messages need to be more descriptive

### ISSUE THREAD

**Issue by bobobo1618** [Storj/statusify#6]
I'm getting `Could not process report` errors from this service and it's impossible to tell why. Looking at [the `put` handler](https://github.com/Storj/data-api/blob/master/methods/report/put.js), it seems there are 3 main failure cases:

- `Report.create`: Indicates that something's likely wrong with the input
- `report.save`: Indicates there's a problem with MongoDB (down?)
- `report.createInElasticSearch`: Indicates there's a problem with ElasticSearch (malformed input like bad timestamp or down)

At the moment neither statusify nor data-api itself propagate these through, it'd be great if they did (and I can submit a pull request to do so if needed).

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
