### ISSUE TITLE
Telemetry report rejected, reason: must start with number, buffer, array or string

### ISSUE THREAD

**Issue by littleskunk** [Storj/statusify#8]
Looks like the fixed telemetry endpoint was published today. Now we have a new error message.
```
{"level":"warn","message":"telemetry report rejected, reason: Cannot read property 'nodeID' of undefined","timestamp":"2017-02-08T22:57:01.323Z"}
{"level":"warn","message":"telemetry report rejected, reason: must start with number, buffer, array or string","timestamp":"2017-02-08T23:07:01.180Z"}
{"level":"warn","message":"telemetry report rejected, reason: must start with number, buffer, array or string","timestamp":"2017-02-08T23:16:59.344Z"}
{"level":"warn","message":"telemetry report rejected, reason: must start with number, buffer, array or string","timestamp":"2017-02-08T23:26:59.299Z"}
{"level":"warn","message":"telemetry report rejected, reason: must start with number, buffer, array or string","timestamp":"2017-02-08T23:36:59.486Z"}
{"level":"warn","message":"telemetry report rejected, reason: must start with number, buffer, array or string","timestamp":"2017-02-08T23:46:59.605Z"}
```

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
